
# This is a Terragrunt module generated by boilerplate.
terraform {
  source = "https://github.com/harness-community/terraform-harness-content.git?ref=v0.4.1"
}

include "root" {
  path = find_in_parent_folders()
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

}
